phone_number:
  max_length: 12
  min_length: 8
address:
  min_length: 10
order:
  total_money_nil: 0
kaminari:
  paginate_comment: 5
ads:
  max_display: 5
delay_time_send_email:
  time_delay: 20
recommend:
  range: 500000
  limit: 3
currency:
  vnd: "VND"
google_map_url: "https://www.google.com/maps/place/"
contact:
  call_for_buy: 1800.1060
  call_to_complain: 1800.1062
  call_for_warranty: 1800.1064
  technical_assistance: 1800.1763
users:
  -
    email: normal_user@gmail.com
    password: "123456"
    password_confirmation: "123456"
    role: 0
    address: "Thanh Xuan - Thanh pho Ha Noi"
    phone_number: "012345678"
  -
    email: admin@gmail.com
    password: "123456"
    password_confirmation: "123456"
    role: 1
    address: "Thanh Xuan - Thanh pho Ha Noi"
    phone_number: "012345678"
makers:
  -
    name: "Apple"
  -
    name: "Oppo"
mobiles:
  -
    name: "iPhone 8 Plus 256GB"
    ram: "2GB"
    price: 1000000
    older_price: 1500000
    sale_time: <%= DateTime.new 2018, 6, 22, 8 %>
    width: "78.1 mm"
    height: "158.4 mm"
    front_camera: "12 MP"
    behind_camera: "12 MP"
    weight: 202
    battery: "2691 mAh"
    resolution_width: 1080
    resolution_height: 1920
    maker_id: 1
    avatar: <%= Rails.root.join("app/assets/images/seed/mobiles/IP 8/avatar.png") %>
    hot_mobile: <%= Rails.root.join("app/assets/images/seed/mobiles/IP 8/hot_mobile.jpg") %>
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
  -
    name: "iPhone Galaxy S8"
    ram: "2GB"
    price: 2000000
    older_price: 2500000
    sale_time: <%= DateTime.new 2018, 6, 22, 10 %>
    width: "78.1 mm"
    height: "158.4 mm"
    front_camera: "12 MP"
    behind_camera: "12 MP"
    weight: 202
    battery: "2691 mAh"
    resolution_width: 1080
    resolution_height: 1920
    maker_id: 1
    avatar: <%= Rails.root.join("app/assets/images/seed/mobiles/Samsung S8/avatar.png") %>
    hot_mobile: <%= Rails.root.join("app/assets/images/seed/mobiles/Samsung S8/hot_mobile.jpg") %>
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
  -
    name: "iPhone 6 Plus 256GB"
    ram: "3GB"
    price: 3400000
    older_price: 3500000
    sale_time: <%= DateTime.new 2018, 6, 22, 9 %>
    width: "78.1 mm"
    height: "158.4 mm"
    front_camera: "12 MP"
    behind_camera: "12 MP"
    weight: 202
    battery: "2691 mAh"
    resolution_width: 1080
    resolution_height: 1920
    maker_id: 1
    avatar: <%= Rails.root.join("app/assets/images/seed/mobiles/IP 6 plus/avatar.png") %>
    hot_mobile: <%= Rails.root.join("app/assets/images/seed/mobiles/IP 6 plus/hot_mobile.jpg") %>
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
  -
    name: "iPhone 7 Plus 256GB"
    ram: "2GB"
    price: 8000000
    older_price: 1000000
    sale_time: <%= DateTime.new 2018, 6, 22, 8 %>
    width: "78.1 mm"
    height: "158.4 mm"
    front_camera: "12 MP"
    behind_camera: "12 MP"
    weight: 202
    battery: "2691 mAh"
    resolution_width: 1080
    resolution_height: 1920
    maker_id: 1
    avatar: <%= Rails.root.join("app/assets/images/seed/mobiles/IP7 plus/avatar.png") %>
    hot_mobile: <%= Rails.root.join("app/assets/images/seed/mobiles/IP7 plus/hot_mobile.jpg") %>
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
  -
    name: "iPhone 4 Plus"
    ram: "2GB"
    price: 4000000
    older_price: 8500000
    sale_time: <%= DateTime.new 2018, 6, 22, 8 %>
    width: "78.1 mm"
    height: "158.4 mm"
    front_camera: "12 MP"
    behind_camera: "12 MP"
    weight: 202
    battery: "2691 mAh"
    resolution_width: 1080
    resolution_height: 1920
    maker_id: 1
    avatar: <%= Rails.root.join("app/assets/images/seed/mobiles/IP 4 plus/avatar.jpg") %>
    hot_mobile: <%= Rails.root.join("app/assets/images/seed/mobiles/IP 4 plus/hot_mobile.jpg") %>
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
  -
    name: "Oppo Neo 3"
    ram: "3GB"
    price: 5500000
    older_price: 7500000
    sale_time: <%= DateTime.new 2018, 6, 22, 8 %>
    width: "78.1 mm"
    height: "158.4 mm"
    front_camera: "12 MP"
    behind_camera: "12 MP"
    weight: 202
    battery: "2691 mAh"
    resolution_width: 1080
    resolution_height: 1920
    maker_id: 2
    avatar: <%= Rails.root.join("app/assets/images/seed/mobiles/Oppo Neo 3/avatar.png") %>
    hot_mobile: <%= Rails.root.join("app/assets/images/seed/mobiles/Oppo Neo 3/hot_mobile.jpg") %>
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
  -
    name: "Oppo Neo 4"
    ram: "2GB"
    price: 8000000
    older_price: 9500000
    sale_time: <%= DateTime.new 2018, 6, 22, 8 %>
    width: "78.1 mm"
    height: "158.4 mm"
    front_camera: "12 MP"
    behind_camera: "12 MP"
    weight: 202
    battery: "2691 mAh"
    resolution_width: 1080
    resolution_height: 1920
    maker_id: 2
    avatar: <%= Rails.root.join("app/assets/images/seed/mobiles/Oppo Neo 4/avatar.png") %>
    hot_mobile: <%= Rails.root.join("app/assets/images/seed/mobiles/Oppo Neo 4/hot_mobile.jpg") %>
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
  -
    name: "Oppo Neo 5"
    ram: "3GB"
    price: 800000
    older_price: 10000000
    sale_time: DateTime.new 2018, 6, 22, 8 %>
    width: "78.1 mm"
    height: "158.4 mm"
    front_camera: "12 MP"
    behind_camera: "12 MP"
    weight: 202
    battery: "2691 mAh"
    resolution_width: 1080
    resolution_height: 1920
    maker_id: 2
    avatar: <%= Rails.root.join("app/assets/images/seed/mobiles/Oppo Neo 5/avatar.png") %>
    hot_mobile: <%= Rails.root.join("app/assets/images/seed/mobiles/Oppo Neo 5/hot_mobile.jpg") %>
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
  -
    name: "Oppo Neo 6"
    ram: "4GB"
    price: 1300000
    older_price: 1500000
    sale_time: <%= DateTime.new 2018, 6, 22, 8 %>
    width: "78.1 mm"
    height: "158.4 mm"
    front_camera: "12 MP"
    behind_camera: "12 MP"
    weight: 202
    battery: "2691 mAh"
    resolution_width: 1080
    resolution_height: 1920
    maker_id: 2
    avatar: <%= Rails.root.join("app/assets/images/seed/mobiles/Oppo Neo 6/avatar.png") %>
    hot_mobile: <%= Rails.root.join("app/assets/images/seed/mobiles/Oppo Neo 6/hot_mobile.jpg") %>
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
  -
    name: "Oppo Neo 7"
    ram: "4GB"
    price: 1400000
    older_price: 1500000
    sale_time: <%= DateTime.new 2018, 6, 22, 8 %>
    width: "78.1 mm"
    height: "158.4 mm"
    front_camera: "12 MP"
    behind_camera: "12 MP"
    weight: 202
    battery: "2691 mAh"
    resolution_width: 1080
    resolution_height: 1920
    maker_id: 2
    avatar: <%= Rails.root.join("app/assets/images/seed/mobiles/Oppo Neo 7/avatar.png") %>
    hot_mobile: <%= Rails.root.join("app/assets/images/seed/mobiles/Oppo Neo 7/hot_mobile.jpg") %>
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
colors:
  -
    name: "Trắng"
  -
    name: "Đen"
  -
    name: "Xám"
mobile_colors:
  -
    mobile_id: 1
    color_id: 1
  -
    mobile_id: 1
    color_id: 2
  -
    mobile_id: 2
    color_id: 1
  -
    mobile_id: 2
    color_id: 3
  -
    mobile_id: 3
    color_id: 3
  -
    mobile_id: 3
    color_id: 2
  -
    mobile_id: 4
    color_id: 1
  -
    mobile_id: 4
    color_id: 3
  -
    mobile_id: 5
    color_id: 2
  -
    mobile_id: 5
    color_id: 3
  -
    mobile_id: 6
    color_id: 1
  -
    mobile_id: 6
    color_id: 2
  -
    mobile_id: 7
    color_id: 1
  -
    mobile_id: 3
    color_id: 1
  -
    mobile_id: 8
    color_id: 2
  -
    mobile_id: 8
    color_id: 1
  -
    mobile_id: 9
    color_id: 1
  -
    mobile_id: 9
    color_id: 2
  -
    mobile_id: 10
    color_id: 1
  -
    mobile_id: 10
    color_id: 3
advertisements:
  -
    title: "Đổi cũ lấy mới"
    maker_id: 2
    image: <%= Rails.root.join("app/assets/images/seed/advertisements/slide1.png") %>
  -
    title: "Giảm Iphone 1 triệu"
    maker_id: 1
    image: <%= Rails.root.join("app/assets/images/seed/advertisements/slide2.png") %>
  -
    title: "Samsung trả góp 0%"
    maker_id: 2
    image: <%= Rails.root.join("app/assets/images/seed/advertisements/slide3.png") %>
  -
    title: "Mua 3 tặng 1"
    maker_id: 2
    image: <%= Rails.root.join("app/assets/images/seed/advertisements/slide4.jpg") %>
  -
    title: "Happy new year 2018"
    maker_id: 1
    image: <%= Rails.root.join("app/assets/images/seed/advertisements/slide5.jpg") %>
images:
  -
    mobile_image: <%= Rails.root.join("app/assets/images/seed/mobiles/IP 8/slider1.jpg") %>
    mobile_id: 1
  -
    mobile_image: <%= Rails.root.join("app/assets/images/seed/mobiles/IP 8/slider2.jpg") %>
    mobile_id: 1
  -
    mobile_image: <%= Rails.root.join("app/assets/images/seed/mobiles/IP 8/slider3.jpg") %>
    mobile_id: 1
citys:
  -
    name: "Hà Nội"
  -
    name: "Hồ Chí Minh"
districts:
  -
    name: "Lê Duẩn"
    city_id: 1
  -
    name: "Nguyễn Văn Cừ"
    city_id: 1
  -
    name: "Thái Hà"
    city_id: 1
  -
    name: "Trần Quang Khải"
    city_id: 2
  -
    name: "Đường 3/2"
    city_id: 2
  -
    name: "Cách Mạng Tháng 8"
    city_id: 2
shops:
  -
    address: "194 Lê Duẩn"
    district_id: 1
    city_id: 1
  -
    address: "382 Nguyễn Văn Cừ"
    district_id: 2
    city_id: 1
  -
    address: "122 Thái Hà"
    district_id: 3
    city_id: 1
  -
    address: "55 Trần Quang Khải"
    district_id: 4
    city_id: 2
  -
    address: "1142-1144 đường 3/2"
    district_id: 5
    city_id: 2
  -
    address: "621D Cách Mạng Tháng 8"
    district_id: 6
    city_id: 2
  -
    address: "621 Lê Duẩn"
    district_id: 1
    city_id: 1
  -
    address: "621D Trần Quang Khải"
    district_id: 4
    city_id: 2
shop_mobiles:
  -
    shop_id: 1
    mobile_id: 1
    amount: 20
  -
    shop_id: 1
    mobile_id: 2
    amount: 20
  -
    shop_id: 2
    mobile_id: 3
    amount: 20
  -
    shop_id: 2
    mobile_id: 4
    amount: 20
  -
    shop_id: 3
    mobile_id: 5
    amount: 20
  -
    shop_id: 3
    mobile_id: 6
    amount: 20
  -
    shop_id: 4
    mobile_id: 7
    amount: 20
  -
    shop_id: 4
    mobile_id: 8
    amount: 20
  -
    shop_id: 5
    mobile_id: 9
    amount: 20
  -
    shop_id: 5
    mobile_id: 10
    amount: 20
  -
    shop_id: 6
    mobile_id: 1
    amount: 20
  -
    shop_id: 6
    mobile_id: 4
    amount: 20
  -
    shop_id: 7
    mobile_id: 3
    amount: 20
  -
    shop_id: 7
    mobile_id: 7
    amount: 20
  -
    shop_id: 8
    mobile_id: 5
    amount: 20
  -
    shop_id: 8
    mobile_id: 10
    amount: 20
